### PR TITLE
Magneto fix

### LINKED ISSUE #73: Magnetometer does not reliably point towards the same location.
The magnetometer is unable to locate the north reliably. This must either be fixed or a different method should be used for displaying direction.

### PR DESCRIPTION
**Pull request by jasperverplanke**
completely overhauld the way the compass works!
 the feel might not be perfect yet though
the old crap is still in there but im afraid to remove it

### CODE REVIEW

File: Project/hardware/src/gyroCompass.c [hunk 1]
```diff
@@ -503,16 +519,17 @@ uint8_t magnetometer_set_sampling_freq(int aFreq)
 {
 	int error = 0;
 	struct sensor_value odr_attr;
-
+	//char * errorstr;
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please clean up unused parts of the code

File: Project/hardware/src/gyroCompass.c [hunk 2]
```diff
@@ -503,16 +519,17 @@ uint8_t magnetometer_set_sampling_freq(int aFreq)
...
 	odr_attr.val1 = aFreq;
 	odr_attr.val2 = 0;
 
 	error = sensor_attr_set(magnetometer, SENSOR_CHAN_MAGN_XYZ,
 							SENSOR_ATTR_SAMPLING_FREQUENCY, &odr_attr);
 	if (error != 0)
 	{
-		LOG_ERR("Cannot set sampling frequency for magnetometer.\n");
-		return 10;
+		//sprintf(errorstr, "Cannot set sampling frequency for magnetometer because: %d", error);
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please clean up unused parts of the code

File: Project/hardware/src/gyroCompass.c [hunk 3]
```diff
@@ -571,16 +590,17 @@ uint8_t magnetometer_exit(void)
 #if defined(CONFIG_BOARD_NUCLEO_H743ZI)
 	if (!magnetometer_is_init)
 	{
+		LOG_ERR("Magnetometer not initialized(e)\n");
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: (e)?

File: Project/hardware/src/gyroCompass.c [hunk 4]
```diff
@@ -571,16 +590,17 @@ uint8_t magnetometer_exit(void)
...
-	// }
+	/*
+	int error = magnetometer_set_sampling_freq(magno_sample_freq_off);
+	if (error != 0)
+	{
+	  return error;
+	}*/
 #endif
-
+	LOG_WRN("Magnetometer exit\n");
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please make the warning more clear on why exiting is warning-worthy.
Did it exit the function? Did it exit from the program entirely and won't be used anymore?

File: Project/hardware/src/gyroCompass.c [hunk 5]
```diff
@@ -605,7 +625,7 @@ uint8_t magnetometer_get_magneto(int16_t *aMagneto)
 
 	if (!magnetometer_is_init)
 	{
-		LOG_ERR("Magnetometer not initialized\n");
+		LOG_ERR("Magnetometer not initialized(g)\n");
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: (g)?

File: Project/hardware/src/gyroCompass.c [hunk 6]
```diff
@@ -618,16 +638,16 @@ uint8_t magnetometer_get_magneto(int16_t *aMagneto)
...
 	magn_xyz_double[1] -= Y_OFFSET;
 	magn_xyz_double[2] -= Z_OFFSET;
-
+	*/
 	// Scale value over max range of int. Value is max 1 or -1
 	for (int i = 0; i < 3; i++)
 	{
 		aMagneto[i] = (int16_t)(magn_xyz_double[i] * 32767);
-	}
+	}
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Trailing tab whitespace

File: Project/hardware/src/gyroCompass.c [hunk 7]
```diff
@@ -914,6 +934,54 @@ uint8_t gyroscope_get_pitch(int *aPitch)
 	return 0;
 }
 
+
+/**
+ *	@brief calibrates the compas then makes it percentile
+ *	call this often to ensure the compass functions well,
+ *	this function recalibrates the compass and percentile direction
+ *	in 2D
+ *  @return if it returns >0 it is changing stuff
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: changing stuff?

File: Project/hardware/src/gyroCompass.c [hunk 8]
```diff
@@ -931,6 +999,7 @@ uint8_t gyroCompass_get_heading(int *aHeading)
 #if defined(CONFIG_BOARD_NUCLEO_H743ZI)
 	int16_t MagnetoValue[3], AccelValue[3];
 	double angle;
+	//char logBuf[32];
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please clean up unused parts of the code

File: Project/hardware/src/gyroCompass.c [hunk 9]
```diff
@@ -939,7 +1008,7 @@ uint8_t gyroCompass_get_heading(int *aHeading)
 	}
 	if (!magnetometer_is_init)
 	{
-		LOG_ERR("Magnetometer not initialized\n");
+		//LOG_ERR("Magnetometer not initialized(H)\n");
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Why did you remove the error log and add (H)?

File: Project/hardware/src/gyroCompass.c [hunk 10]
```diff
@@ -959,13 +1028,16 @@ uint8_t gyroCompass_get_heading(int *aHeading)
 		return 3;
 	}
 
+	//i do not trust the next function, it might not be needed anyway
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please keep in mind that a new programmer might read this with barely any clue of the project. How will this comment help?

File: Project/hardware/src/gyroCompass.c [hunk 11]
```diff
@@ -959,13 +1028,16 @@ uint8_t gyroCompass_get_heading(int *aHeading)
...
 	errorCode = gyroCompass_i_ecompass(MagnetoValue[0], MagnetoValue[1], MagnetoValue[2], AccelValue[0], AccelValue[1], AccelValue[2], &angle);
 	if (errorCode)
 	{
 		return 3;
 	}
+	//this function recalibrates and returns percentile
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Please explain what a function does above it's declaration, not 100 lines down.

File: Project/hardware/src/gyroCompass.c [hunk 12]
```diff
@@ -36,6 +36,22 @@ const int16_t K3 = 446;
 /* Final step size for iDivide */
 const uint16_t MINDELTADIV = 1;
 
+/**
+ * @brief Calculates the angle in degrees based on x and y.
+ * @param[in] x value of the x-axis
+ * @param[in] y value of the y-axis
+ * @return angle in degrees (0-359)
+ * @return < 0 on error
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: It only returns the angle, I'm not seeing any negative return for an error

**Review by TotallyOriginalUsername — CHANGES_REQUESTED** [review]

**Comment by TotallyOriginalUsername** [comment]
Also please remove old code if it isn't used anymore, the code should not break if it is removed (or you'll learn why the old code was there)

**Comment by jasperverplanke** [comment]
i removed a lot of code that i assumed did nothing, i did not encounter anything odd during testing.

i did not test the Pokémon game. although i doubt it got worse i simply cannot guaranty value of code that is not tested anywhere.

there might totally be a ton of useless code concerning  the accelometer (and possibly gyroscope).  yet it is out of scope for this pull request and likely this entire project.

**Comment by TotallyOriginalUsername** [comment]
I ment the magneto-related parts of the code, so someone can't use the not working functions on accident, accelometer and gryoscope are indeed out of scope

**Comment by jasperverplanke** [comment]
> I ment the magneto-related parts of the code, so someone can't use the not working functions on accident, accelometer and gryoscope are indeed out of scope

Every legacy function related to the magnetometer that i am aware of is removed, i see no further improvements for this PR.

File: Project/hardware/src/gyroCompass.c [hunk 13]
```diff
@@ -618,11 +435,11 @@ uint8_t magnetometer_get_magneto(int16_t *aMagneto)
 		magn_xyz_double[i] = sensor_value_to_double(&magn_xyz[i]);
 	}
 
-	// Subtract the hard iron offset
+	/* //Subtract the hard iron offset
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: The hard iron offset isn't being used anymore(line 777 also mentions this), so this can be removed instead of commented out

File: Project/hardware/src/gyroCompass.c [hunk 14]
```diff
@@ -914,6 +731,55 @@ uint8_t gyroscope_get_pitch(int *aPitch)
...
 }
 
+
+/**
+ *	@brief calibrates the compas then makes it percentile
+ *	call this often to ensure the compass functions well,
+ *	this function recalibrates the compass and percentile direction
+ *	in 2D
+ *  @return if it returns >0 it is widening the calibration 
+ * 	if this number is high constantly it is a sign of high magnatic interference
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: When is the number high?

File: Project/hardware/src/gyroCompass.c [hunk 15]
```diff
@@ -930,7 +796,7 @@ uint8_t gyroCompass_get_heading(int *aHeading)
 {
 #if defined(CONFIG_BOARD_NUCLEO_H743ZI)
 	int16_t MagnetoValue[3], AccelValue[3];
-	double angle;
+	//double angle;
```
Comment (TotallyOriginalUsername) [inline Project/hardware/src/gyroCompass.c]: Can be removed

**Review by TotallyOriginalUsername — CHANGES_REQUESTED** [review]

**Review by kasper201 — APPROVED** [review]

**Review by TotallyOriginalUsername — APPROVED** [review]
